# Set Context Path
server:
  servlet:
    context-path: /customer-data

# Spring DATA JPA and Hibernate Properties
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop

# Enabling H2 Console (spring.h2.console.enabled)
  h2:
    console:
      enabled: true